version: "3.7"
services:
  qbittorrentvpn:
    image: dyonr/qbittorrentvpn
    container_name: qbittorrentvpn
    privileged: true
    dns:
      - ${DNS_IP}
    environment:
      - VPN_ENABLED=yes
      - VPN_TYPE=wireguard
      - LAN_NETWORK=192.168.0.0/24
      - WEBUI_PORT=${APP_PORT}
      - NAME_SERVERS=1.1.1.1
      - HEALTH_CHECK_HOST=www.google.com
      - HEALTH_CHECK_INTERVAL=300
      - HEALTH_CHECK_AMOUNT=10
      - HEALTH_CHECK_SILENT=0
      - ADDITIONAL_PORTS=6881
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${ROOT_FOLDER_HOST}/media/downloads:/downloads
    ports:
      - ${APP_PORT}:${APP_PORT}
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
    networks:
      - tipi_main_network
    labels:
      # Main
      traefik.enable: true
      traefik.http.middlewares.qbittorrentvpn-web-redirect.redirectscheme.scheme: https
      traefik.http.services.qbittorrentvpn.loadbalancer.server.port: ${APP_PORT}
      # Web
      traefik.http.routers.qbittorrentvpn-insecure.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.qbittorrentvpn-insecure.entrypoints: web
      traefik.http.routers.qbittorrentvpn-insecure.service: qbittorrentvpn
      traefik.http.routers.qbittorrentvpn-insecure.middlewares: qbittorrentvpn-web-redirect
      # Websecure
      traefik.http.routers.qbittorrentvpn.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.qbittorrentvpn.entrypoints: websecure
      traefik.http.routers.qbittorrentvpn.service: qbittorrentvpn
      traefik.http.routers.qbittorrentvpn.tls.certresolver: myresolver
      # Local domain
      traefik.http.routers.qbittorrentvpn-local-insecure.rule: Host(`qbittorrentvpn.${LOCAL_DOMAIN}`)
      traefik.http.routers.qbittorrentvpn-local-insecure.entrypoints: web
      traefik.http.routers.qbittorrentvpn-local-insecure.service: qbittorrentvpn
      traefik.http.routers.qbittorrentvpn-local-insecure.middlewares: qbittorrentvpn-web-redirect
      # Local domain secure
      traefik.http.routers.qbittorrentvpn-local.rule: Host(`qbittorrentvpn.${LOCAL_DOMAIN}`)
      traefik.http.routers.qbittorrentvpn-local.entrypoints: websecure
      traefik.http.routers.qbittorrentvpn-local.service: qbittorrentvpn
      traefik.http.routers.qbittorrentvpn-local.tls: true